### ISSUE TITLE
Improve RSS feed

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#104]
Can you tell me a little more about how the excerpts will work for posts? I've never used them but with the new design, FB, Pinterest and other social media are pulling the first couple sentences automatically as text, and of course an assigned excerpt will be better. 

In the documentation you gave me, you include [this link](https://en.support.wordpress.com/excerpts/) to learn more but I don't see an Excerpt field in the sidebar of the editor (hope I'm not just missing it).

Finally, my posts used to break where I used the "More" tag, I'd place it after the first paragraph. In the new design, they're breaking elsewhere, sooner. This isn't a huge issue but I want to make sure if I start using excerpts that the beginning of the post will show before the break on the index pages, and not just the excerpt.

Hope this all makes sense. Thanks!

Updated to add further issues: I have a email that goes out automatically daily from the RSS feed to 80K (!) people and every single one of them received a blank email today and I cannot figure out what broke by looking around. (I have hundreds of angry emails.) Yesterday, the RSS feed was showing in full (it used to only run until the "More" break, which was my preference because there are so many site scrapers that use RSS) so I went and changed the "For each article in a feed, show Full text or Summary" from full text to summary and now this happened. I could use help on how to get this right before the next update goes out and I lose all my subscribers.

**Comment by sarahmonster** [comment]
I think, having done some further research and experimentation, that the way to go here might be to build a custom feed for the site: https://vip.wordpress.com/documentation/vip-development-tips-tricks/altering-feeds/

Functionality-wise, here's what we want: feeds should ideally show the post content up to the  tag, then a link to the full post. If an excerpt is present for the post, that should *not* be used. 

I've started on a PR (#127) to resolve this, but testing the feeds is a bit tricky, particularly on a live site, so it'll need more work before it's ready to deploy on the live site. Different feed readers also use different parts of the feed, so that's tricky as well.

**Comment by sarahmonster** [comment]
@debperelman I've just pushed an update that should change the feed behaviour so it's more closely aligned with what you're looking for: posts will break at the more tag now automatically. 

Some feed readers may still show the excerpt, but most will display the post content, up to the more tag, followed by a "read more" link to the full post. 

You can see the new feed in action here: http://feeds.feedburner.com/smittenkitchen Viewed directly in Chrome or Safari, you'll see the post content. Firefox displays the excerpt, but I think this is much less common behaviour. 

Here's what it looks like in Feedly:

<img width="1068" alt="screenshot 2016-09-28 15 17 19" src="https://cloud.githubusercontent.com/assets/376315/18917216/08838db2-858f-11e6-8686-6b06510dcd00.png">

I think this should resolve this issue for you—you won't need to worry about doubling up content for the excerpts, and you can now use this field for pithy summaries instead. 😄

**Comment by debperelman** [comment]
Hi @sarahmonster -- Thank you, I'm glad this is sorted. 

I have a bunch of questions: First, how can we get the top photo to display in the feed? Without it, the feed still isn't as before and with a very truncated post that is just the top photo and one paragraph, readers won't ever see what the dish looks like.

Second, does this mean I no longer have to copy half the post into the excerpt box as I have been? If so, can I begin to use the excerpt box for an actual excerpt (one liner for search results) or will that override the feed again?

Finally, can I expect the "read the rest" or "more" to show up in the feed readers to indicate that the post has been truncated? It hasn't been since I've been using the excerpt box (but worked with my previous setup) and this sounds like it wouldn't be a big deal but I have gotten an *unbelievable* amount of email and comment complaints about this. As in, I stopped counting at 30 emails...

Thank you.

**Comment by sarahmonster** [comment]
> First, how can we get the top photo to display in the feed? Without it, the feed still isn't as before and with a very truncated post that is just the top photo and one paragraph, readers won't ever see what the dish looks like.

I've made an update to the custom feed that adds the featured image to each post. It now looks like this:

![smitten kitchen](https://cloud.githubusercontent.com/assets/376315/18924907/c872c54c-85a9-11e6-87e2-bb3f03b7d3ae.png)

> Second, does this mean I no longer have to copy half the post into the excerpt box as I have been? If so, can I begin to use the excerpt box for an actual excerpt (one liner for search results) or will that override the feed again?

Yes, you can use the excerpt for an actual post summary now. Feed readers will only use the post content, broken at the "more" tag.

> Finally, can I expect the "read the rest" or "more" to show up in the feed readers to indicate that the post has been truncated?

Yep! It's part of the feed text, so it will show in all feed readers. The screenshot above was taken from Feedly, a common web-based feed reader, and is illustrative of how the posts will look in a reader. You can preview it yourself here: https://feedly.com/i/subscription/feed/http://feeds.feedburner.com/smittenkitchen
