### ISSUE TITLE
Improve print behaviour

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#108]
1. There are two print templates for recipes, the one from a "Print" link in the recipe card (leads to an unformatted page) and the one in the print icon (leads to a formatted page). The first I think should be the same as the second. 

2. The second readers are unhappy with because they want recipes to print (except when they're very long) on one page again. Is it possible to use a smaller font size and tighter line spacing so that most recipes will fit on one or at most two pages? There were also a few requests for a darker font color so it's easier to read.

3. The first print link, the in the recipe card, doesn't print from phones or tablets.

4. Finally, it would be great to have the site's logo back on top. Recipe printouts tend to get distributed far and wide and I'd love if we can make them as professionally reflective of the site they came from as possible. Thank you.

**Comment by debperelman** [comment]
Thanks for taking a closer look. The print template is now completely scrambled for me (logo out of place, title listed twice, various lines). I'm attaching the PDF. I use Chrome.
[eggplant with yogurt and tomato relish – smitten kitchen.pdf](https://github.com/a8cteam51/smittenkitchen/files/384826/eggplant.with.yogurt.and.tomato.relish.smitten.kitchen.pdf)

I will ask the ad people about how to not make it appear.

**Comment by sarahmonster** [comment]
I've hidden the recipe title, which solves the "double title" issue you were seeing.

As for the overlapping logo, I'm unable to reproduce this error, either in Chrome or Firefox. I've added some code that may resolve this issue, but without the ability to reproduce it's a bit tricky to tell for sure. Can you let me know if you're still seeing the problem?

**Comment by debperelman** [comment]
It looks better this morning so it might have been scrambled due to cache-ing issues. Plus, nobody else reported it and someone always does. :)

Recipes that go over two pages still don't have any margin at the bottom of the first page and top of the second, so the last line will print right to the bottom of the page and the first line will print right at the top. I imagine this will be cut off on most printers.

Additional request: I'd like to add a footer to each page, small font, maybe small caps. Ideally, it would have the copyright field at the footer of the website and the date field that's in the recipe would go there instead: 

 First published on [insert date here] on smittenktichen.com | ©2009–2016 Smitten Kitchen

**Comment by debperelman** [comment]
Re, removing the ad from the print template, my ad team sent this over:

> One quick fix for this is to make a css rule that reads like this:
> 
> <style type="text/css" media="print">


> .no-print
> { display: none; }
> </style>
> 
> Which will make it so when any element has the class "no-print" it will not display when being printed. I've attached a html document that if you open in a web browser and open up a print preview will demonstrate the functionality. If the dev team ads this class to the container holding ads it should make them disappear when printed. Just have them make sure sure it only targets media="print" or it will be hidden everywhere. 
> 

I imagine you don't need the HTML document to put this fix in, right? Thank you.

**Comment by sarahmonster** [comment]
I've re-added the site footer with the extra text. I changed the text slightly because "First published July 26, 2016 on smittenkitchen.com" sounded less awkward than the on-on of "First published on July 26, 2016 on smittenkitchen.com". 

I've also added a margin to the page to counteract the issue you were experiencing. Do let me know if you require any further adjustments here.

**Comment by debperelman** [comment]
Looks great; thank you.

**Comment by debperelman** [comment]
I'm sorry, can we fix one more thing: Can we remove the top larger title of the post? It's the same as the recipe title, so redundant and if we remove it, more recipes will print on one page. Thank you.

**Comment by sarahmonster** [comment]
This was fixed over a week ago in b5e7b8c. I'm not seeing it for any posts in either Firefox or Chrome. Can you let me know which posts this happens for, and in which browsers, and I can investigate further?

**Comment by sarahmonster** [comment]
@debperelman can you let me know if you're still having issues with this?

**Comment by debperelman** [comment]
I'm sorry -- it must have just been another cacheing issue; it looks fine now. Thanks.
