### ISSUE TITLE
comment sorting maybe not working perfectly yet

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#110]
Readers are, by and large, very happy that there are comment sorting options but I don't think it's working perfectly yet. It sounds like when I reply to a comment, it's not necessarily showing up in the I Made This or I Have a Question tab that it was asked in, just the main thread. Is there a certain way I'm supposed to be responding? I respond through the comment portion of the admin panel, using the reply link to each comment. The only way I can stay on top of new comments on 1000+ posts as they come in is to read them this way.

**Comment by michiecat** [comment]
Hi @debperelman -- I've _almost_ got this one fixed. So far I'm able to sort two levels of comments, but I'm still working on a way to have the sorting recognize further levels of comments (e.g. replies to replies). Thanks for your patience!

**Comment by michiecat** [comment]
OK, I think I have a solution. I'll do some more testing tomorrow and push out a fix. Overall, the nesting can break and do strange things when people check "I have a question" or "I made this" when replying to comments. @debperelman how do you feel about removing those two checkboxes on comment replies? This way, only parent-level comments get the extra options, while their replies (children, grandchildren, great-grandchildren, etc) automatically get sorted in the same place as their parent.

**Comment by debperelman** [comment]
Thanks for your work on this. I think what you're suggesting makes a lot more sense. A reply needs to live where it started, after all. Just to clarify: the front tab (All) will still have all the comments, replies and everything else, yes?

**Comment by michiecat** [comment]
@debperelman yes, that's correct. The "All" tab will still show everything, while the other two tabs will sort depending on which checkbox was selected in the top-level comment for each thread. I will push the fix out in a little bit!

**Comment by michiecat** [comment]
@debperelman I've deployed the fix to the live site after testing it out. Let me know if you notice any issues! I'll leave this issue open for a bit just incase anything comes up.

**Comment by debperelman** [comment]
From what I can see, it's working well now. I can reopen if I see more trouble. And thank you. You've created one of the most loved features on the new site, something people on recipe sites have been asking for forever.

**Comment by michiecat** [comment]
I'm so glad to hear that! Yes, do reopen if there are any other issues with the comment sorting.
