### ISSUE TITLE
is it possible to have the search bar default open on desktop only?

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#113]
I'm hearing from a lot of readers that they miss having a search bar they don't have to click to open on desktop. (Tablet and mobile readers, I think, expect to have to click a search icon by now.) Because there is so much extra space on desktop, especially in the sidebar, is this something that would be possible? I did love having a giant search bar right under the logo in the old site. Thank you.

Update: I found a widget option for a search bar and added it up top. However, it's not styled or anything (not a huge deal) and is of course redundant with the search icon. But it's a good temporary fix!

**Comment by debperelman** [comment]
I think this request fell into the abyss but several readers have told me recently how it drives them crazy that the newsletter subscription bar is open and *looks* like a search bar while the search on desktop is closed unless clicked on. I need to have both at the top of desktop but differentiated. I'd like the search bar to default to an open position on desktop to make it more clear. Thanks.

**Comment by danielwrobert** [comment]
Hi Deb! Sorry about the delay on this.

I'm thinking it might be best to add a search bar at the top of the sidebar on desktop only. Then hide the toggling search in the nav.

The mobile view will remain as is. If that sounds good to you, I'll go ahead and implement it.

Thanks!

**Comment by debperelman** [comment]
Sorry for the delay but that would be perfect. Thank you.

**Comment by danielwrobert** [comment]
Fixed and deployed. Thanks!
