### ISSUE TITLE
author highlight comments are highlighting non-author comments

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#117]
An example here: https://smittenkitchen.com/2016/07/welcome-to-the-shiny-new-smitten-kitchen-2-0/#comment-835369

The comments that have replied below my reply are also shaded gray, as if I'd left them.

**Comment by michiecat** [comment]
Addressed in https://github.com/a8cteam51/smittenkitchen/commit/efde42ad33cf055267d86811d45f3a91b4628b74

**Comment by michiecat** [comment]
@debperelman I've pushed a fix for this. If all looks good we can close this one out.
