### ISSUE TITLE
Share-via-email functionality

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#118]
On this, too, perhaps related to the more/excerpts/RSS issue, readers are only getting the title and a link to the rest of the post and also the captcha asks for two words to be entered but instead displays one number. (The number works, it's just confusing.) Thank you.

**Comment by sarahmonster** [comment]
I've asked around, and it seems as though it isn't possible to customise the emails sent out by WordPress.com, beyond adding your logo.

To add a logo, you'll need to add a Gravatar for thesmitten@gmail.com, the email address associated with your WordPress.com account. To set that up, just go here: https://secure.gravatar.com/site/wpcom/

**Comment by debperelman** [comment]
I'd like to start using a plugin to control the template. It's not optional that I cannot control the way it looks, given how widely my work ends up distributed this way. Can I install plugins myself? This one looks promising: https://wordpress.org/plugins/wp-better-emails/

**Comment by michiecat** [comment]
Hi @debperelman -- a note about how plugins work on WordPress.com VIP:

There's collection of plugins that are reviewed and maintained by the WordPress.com VIP team:

https://vip.wordpress.com/plugins/

Those are plugins you can start using immediately right out of the box. You can activate them from your Dashboard under "VIP > Plugins & Services".

If you want to use a plugin outside of that list, we would need to review it for security, code quality, and compatibility with the WordPress.com platform (https://vip.wordpress.com/documentation/vip/code-and-theme-review-process/#plugin-review). This is part of what keeps WordPress.com so safe and stable!

As for the plugin you mentioned, unfortunately it wouldn't be compatible on the WordPress.com platform. We're not able to run any plugins that generate mail, as per these guidelines (https://vip.wordpress.com/documentation/vip/code-review-what-we-look-for/#generating-email) which I've quoted below: 

> To prevent issues with spam, abuse or other unwanted communications, your code should not generate, or allow users to generate, email messages to site users or user-supplied email addresses beyond the core “subscribe” features offered on WordPress.com. That includes mailing list functionality, invitations to view or share content, notifications of site activity, or other messages generated in bulk. Where needed, you can integrate third-party services that allow sharing of content by email, as long as they don’t depend on WordPress.com infrastructure for message delivery.

As Sarah mentioned in her response, it's not possible to customize the emails WordPress.com sends out beyond adding a logo. However the last line in the quote above does say that you can integrate with a third-party/external service that allows sharing of content by email. This week I'll check with the VIP team to find out if other VIP sites have done this, and if so, which services they've used and if they allow email customization.

**Comment by michiecat** [comment]
@debperelman after speaking with the VIP team, they noted that if you'd like to have more control over the sharing functionality, they suggested implementing the [ShareThis plugin](http://www.sharethis.com/get-sharing-tools/) as a free option, or [SailThru](https://getstarted.sailthru.com/) as a paid option. SailThru has a partnership with WordPress.com VIP. Both require that you have an account on their respective services. I am not familiar with either one, and I'm not sure if they would provide the functionality that you're looking for. However if you're interested we can research further.

**Comment by sarahmonster** [comment]
Closing this issue since it's been stagnant since August. @debperelman please do feel free to re-open the issue if you'd like to discuss further.
