### ISSUE TITLE
need to remove one ad and add two others

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#121]
Unfortunately, the desktop banner ad isn't working out -- we need to remove that entirely. 

Instead, I'd like to put in a 300x250 ad in two places: 
1. On individual post pages, after the "Like this post? Subscribe for more!" field and the navigation arrows below it and above the "Leave a reply"
2. On all index pages, after the first two posts, or, between the 2nd and 3rd post, centered.

I'm attaching the new code for these. From the ad team:

There are two steps to adding the unit:
Add the "defineslot" code snippet to the DFP header
Place the div tag where you would like the add to appear in the <body> of the HTML 

[SK_300x250_Mid.txt](https://github.com/a8cteam51/smittenkitchen/files/374649/SK_300x250_Mid.txt)

Thank you.

**Comment by debperelman** [comment]
Thank you -- this looks great everywhere except one place, the recipe index pages. See here: https://smittenkitchen.com/recipes/grilling/?format=list

Is it possible to place the ad on these pages not breaking up the initial list but at the bottom of it?

**Comment by sarahmonster** [comment]
Done!
