### ISSUE TITLE
can I change "(more...)" to "Read more >>"

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#124]
I'd seen an option to change this before, but cannot find it again.

If possible, I prefer a font differentiation for this because it's not part of the paragraph reading, something like small caps but in the link color.

Thank you.

**Comment by sarahmonster** [comment]
This has been added now and is live on the site.

**Comment by debperelman** [comment]
Can you make the >> larger? It's very tiny and looks almost like a bullet point now. Thank you.
