### ISSUE TITLE
google analytics stopped tracking when site moved to VIP

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#129]
It just came to our attention that the site's analytics stopped tracking when we moved servers. What's the best way to set this up?

From Google Analytics, it says we should copy and paste this code into every webpage I want to track:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1185356-1', 'auto');
  ga('send', 'pageview');
```

</script>

There's also an optional PHP implementation section. I can send those instructions if needed.

Thank you.

**Comment by michiecat** [comment]
@debperelman WordPress.com VIP has a plugin for Google Analytics (https://vip.wordpress.com/documentation/integrating-google-analytics/). All we'll need is your tracking ID (which you provided in the code above). On Monday I'll add the plugin to your site. I'll notify you here after I've done so.

**Comment by michiecat** [comment]
@debperelman I've added the plugin to your site and entered your Google Analytics tracking ID. You can manage the plugin settings by going to Settings in your Dashboard and clicking on "Google Analytics".

**Comment by debperelman** [comment]
Thank you.
