### ISSUE TITLE
images broken on a lot of static pages

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#130]
I cannot figure out why this is happening. Examples:

https://smittenkitchen.com/brunch/
https://smittenkitchen.com/dinner-party-menus/
https://smittenkitchen.com/notes-and-tips-from-rome/

**Comment by michiecat** [comment]
It appears that these images were either not imported properly or their file names may have changed, because the error I'm seeing on them is a 404 not found. On Monday I'll look through the backup of the uploads folder that we have and see what I can recover. In the meantime, if you can locate any other pages with missing images, that would be helpful. Thank you!

**Comment by michiecat** [comment]
@debperelman I'm not _exactly_ sure what happened with the images, but they're referencing incorrect file names. The correct images all do exist inside the media library, but we'll need to manually add them back. I'll check with Sarah as well to see if she might have any insights. I fixed the pages you listed above. The following additional pages have broken images. Before I start on the fixes, can you let me know which pages are still in use? Thanks!

https://smittenkitchen.com/soup-recipes/
https://smittenkitchen.com/pumpkin-winter-squash-recipes/
https://smittenkitchen.com/recipe-collections/
https://smittenkitchen.com/gift-worthy/
https://smittenkitchen.com/events/previous-events/
https://smittenkitchen.com/events/
https://smittenkitchen.com/debs-new-york/
https://smittenkitchen.com/cookie-recipes/
https://smittenkitchen.com/chocolate/
https://smittenkitchen.com/apples/
https://smittenkitchen.com/breakfast/
https://smittenkitchen.com/party-food/
https://smittenkitchen.com/thanksgiving/

**Comment by sarahmonster** [comment]
I suspect that this issue is related to the problematic import process—it's easiest to just fix manually at this stage unless there's a programmatic way to determine the new file names.

**Comment by debperelman** [comment]
@michiecat Ideally, these pages would all look good because there are a lot of links to them throughout the site, however, for 90% of them, the new (awesome) recipe index pages can replace these hand-built pages (i.e. just the apple or chocolate or breakfast recipes are easy to show). In terms of active use, however, these are the important ones: 

https://smittenkitchen.com/debs-new-york/
https://smittenkitchen.com/events/
https://smittenkitchen.com/events/previous-events/

I also have found many posts with broken images, probably due to the same issue. I can make a list or hopefully once this is "fixed" it might fix all the broken images across the site? (Crossing my fingers.)

Thanks.

**Comment by sarahmonster** [comment]
@debperelman I've looked into this and unfortunately it doesn't seem like there's a programmatic way of fixing the broken images. If you can provide a list of posts, we can investigate further, but they may need to be fixed manually.

I've fixed the page referenced above, but I couldn't find any instances of broken images on either https://smittenkitchen.com/events/ or https://smittenkitchen.com/events/previous-events/. Can you let me know where there are missing images?

**Comment by debperelman** [comment]
I had to remove the Events and Previous Events broken images because they're active pages. Here's an example of a page that's very messed up that the new recipe index replaces the functionality of, but would be good to get in order because Google is still sending people who search for cookies there: https://smittenkitchen.com/cookie-recipes/ Thank you.

**Comment by sarahmonster** [comment]
Given that the work here is entirely manual—ie, fixing these pages is just a matter of editing the pages in question and re-adding the images from the media library—would it be possible for you to take care of fixing them? This would allow us to spend more time focussing on the more programmatic aspects of the site that can't be fixed manually.

**Comment by debperelman** [comment]
What's strange to me is that I don't think those photos were ever hosted on the site, just Flickr. Did it somehow port them over and that's what causing all the broken images? 

As an easier fix, however, because it would take forever to rebuild that page, can we set up a redirect from it to this newer, better one: https://smittenkitchen.com/recipes/sweets/cookie/?format=photo ?

Thanks.

**Comment by debperelman** [comment]
Here's another one: https://smittenkitchen.com/soup-recipes/ I think it would be easiest if it could redirect to this page: https://smittenkitchen.com/recipes/soup/?format=photo

Am I able to set up redirects on my own? If so, I could probably do the rest of them, as it looks like all of these old handbuilt index pages are scrambled and there are many links across the site going to them.

**Comment by sarahmonster** [comment]
There were a few issues with the image imports when we moved the content over, and I'm guessing what's happened here was a trickle-down effect from that.

Redirecting the pages sounds like a really good solution, and it's super easy to do!

There's a plugin I installed on your site a while ago that allows you to enter redirects via the admin panel. You can find it under [Settings > Safe Redirect Manager](https://smittenkitchendotcom.wordpress.com/wp-admin/edit.php?post_type=redirect_rule). I've just added rules for /soup-recipes and /cookie-recipes so you can see how it works, but it's pretty straightforward. 

To add a new rule, just enter the rule in the panel above. Delete (or convert to draft) the original page just in case there's any confusion. If the rule doesn't take immediately, try [flushing rewrite rules for the site](https://smittenkitchendotcom.wordpress.com/wp-admin/admin.php?page=rewrite-rules-inspector)

Let me know how that works—I'll add a section about rewrite rules to your documentation for future reference.

**Comment by debperelman** [comment]
Very cool! Glad to have this under my control; I can slowly get rid of all of those dated pages. Thanks.

**Comment by sarahmonster** [comment]
You're quite welcome! I am going to close this issue since it doesn't require any action on our end; but as always, please do feel free to re-open if needed.
