### ISSUE TITLE
need to create cname for newsletter ad server

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#131]
These are the instructions from my ad team: 

1) We will need to create a CNAME for SmittenKitchen: li.smittenkitchen.com 

More information about a CNAME HERE https://support.liveintent.com/hc/en-us/articles/205127390-Setting-up-your-CNAME, but essentially, it is a subdomain associated with your brand that will appear within the LiveIntent tags. The CNAME(s) allows email filters to see and recognize the links in the email as belonging to your brand.

2) Most likely your contact at WordPress should be able to create this CNAME for you. But let us know if that is not the case!

3)  After creating the CNAME, have the developer "point" it to the following url.

008ed56aaeb849591ab28e41037d250c.edgesuite.net

**Comment by michiecat** [comment]
@debperelman I've just created the CNAME "li.smittenkitchen.com" as an alias of "008ed56aaeb849591ab28e41037d250c.edgesuite.net".

**Comment by debperelman** [comment]
Thank you!
