### ISSUE TITLE
Adjust formatting of comments

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/smittenkitchen#132]
From #126 and #98:

> Comment line height and name size: This is a bigger concern in the comment section, where there's a lot of space between each comment. I'd like to look into tightening these up. To scroll through 100+ comments (an average on newer posts, much higher on older ones) on a phone with such wide spacing can take forever, and discourages readers from reading through before leaving their own (possibly redundant) question. The names of commenters could be in a slightly smaller font size without taking anything away from the design.

> I'd like to see the names smaller, I think we could tuck the date link next to the reply on the bottom so each comment takes up less space. I think it would also help if the "child" comments were a little more indented or perhaps each had a tiny, subtle down/right arrow denoting that they're responses from an above thread. As one scrolls down the page and reaches a bunch of response comments in a row, it's not clear that they're not top-level comments.

Comment formatting needs an overall design review now that we have content to test with.

**Comment by debperelman** [comment]
FWIW, I've always felt that the comments on my friend Jo's site had a good clean look to the footer (while also providing all of the necessary information): http://cupofjo.com/2016/08/juicy-tomato-hummus-toast/#more-93645

Thank you.

**Comment by sarahmonster** [comment]
I've totally revamped the formatting of comments in #138 and have deployed to the live site—should be a lot better now, both in terms of design & functionality. Do let us know if any additional adjustments are required!

**Comment by debperelman** [comment]
Thank you -- this looks great; much more clean and space-efficient.

I don't know if this needs to be a new ticket, but I'm wondering if it is possible to only have the dashed line separating comments that are the last in the grouping; i.e. if there's one comment and no responses, a line underneath it, but if there are a few responses, only a dashed line under the last one in the grouping. I think this would make it easiest for readers to visually groups conversations.

**Comment by sarahmonster** [comment]
Done! Do let me know if any further adjustments are required here.
