### ISSUE TITLE
Author highlight inconsistently applied

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#136]
This is usually happening on replies or sub-replies, and not all the time. See screenshot. This is that comment's url: https://smittenkitchen.com/2016/07/eggplant-with-yogurt-and-tomato-relish/#comment-838592 I've seen it a few other places too.
![screen shot 2016-08-07 at 12 19 44 pm](https://cloud.githubusercontent.com/assets/16911319/17463694/8ff4c9c4-5c99-11e6-9152-86abc70c92c4.png)

**Comment by sarahmonster** [comment]
This should be looked at in tandem with #132.
