### ISSUE TITLE
titles on recipe page images not linked

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#141]
Basically, on the image cards in the index, you can click anywhere on them to go to the link _except_ for the words. The words seem to be outside the link structure. I've been meaning to flag this issue since I noticed it a while ago, but the following email from a readers/developer this morning more or less did the work for me:

> I noticed a little bug on the recipe page and wanted to report it for y'all as thoroughly as I could. (What can I say, I'm a developer myself, bug reports that say, "this is broken" make me grouchy :))
> 
> On recipe pages, the title of the recipe is not included in the link. You can click all around the image but if you click on the title itself, it's not a link.
> 
> Gif: https://cl.ly/0K0p0X070f36
> 
> This is happening because the header element is not inside the a link. Here's a gif that shows that: https://cl.ly/2B0Q3N1D2701 — this might be confusing if you're not a developer but hopefully it helps! In the gif I am showing that the header element with class .entry-header (yellow) is outside of the link element (red, the whole image); I copy it, delete it, and paste it inside the link, and then you can see that when I hover over the text, it has the pointer cursor and the link works.
> 
> I don't know how the setup is with wordpress but moving the .entry-header inside the link SHOULD solve it. You may need to make some small CSS style tweaks; for example, the right-margin on .entry-header is unnecessarily large, and it may need different vertical spacing if you move it inside the link.
> 
> Interestingly this does NOT happen on the recipe/season links in the sidebar — they have their titles properly inside the link.

Hopefully this is very easy to fix? Thanks.

**Comment by elyseholladay** [comment]
Not to be incredibly creepy (thanks google!), but I was the one that reported this and I'm happy to help/submit a PR if that's useful :) @sarahmonster

**Comment by sarahmonster** [comment]
Hi @elyseholladay! For sure, I'd be delighted to look at a PR! I've been wrapped up in other projects and haven't had an opportunity to look into this yet. 😺

**Comment by elyseholladay** [comment]
@sarahmonster lovely! thank you :) i'll go through the install instructions and see what i can do; i don't typically work on WP or with vagrant (we use docker).

**Comment by elyseholladay** [comment]
Hey @sarahmonster I haven't forgotten about this. Sadly I am hung up on getting the WP VIP Quickstart running with Vagrant; it seems most everything installs yet I end up with a Vagrant error I can't track down. Will attempt it again this week when I have some time, but I don't want to submit an un-tested PR for you. Sorry!

**Comment by sarahmonster** [comment]
No worries, @elyseholladay! I think this should be a relatively simple fix; just haven't had a chance to investigate it myself. 

If you have a PR that you'd like to push, please do feel free to do so and I can test it out and/or build on it. 😄 

Also, if VIP Quickstart is giving you troubles, you may be able to get some help on the Github repo: https://github.com/Automattic/vip-quickstart/

Cheers!
