### ISSUE TITLE
search results: only 10 results showing, "older posts" not working

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#144]
See: https://smittenkitchen.com/?s=chicken

The button that would load the remaining posts isn't working.

**Comment by debperelman** [comment]
Can I bump this? I've gotten dozens of complaints about the search not working past 10 results this week alone.

**Comment by danielwrobert** [comment]
This appears to be an issue with ElasticSearch that was added to the site to improve the search functionality. See #111.

To remedy this, I have disabled Infinite Scroll on the search results pages. This is a known issue and there is, unfortunately, there is no other existing solution at the moment.

I am going to lower the priority on this, since the functionality is fixed. However, I am leaving the ticket open for @sarahmonster to fine-tune the design around the post results navigation links.

**Comment by debperelman** [comment]
Thanks for trying to fix this -- is there another way we can do this without removing the infinitive scroll? This makes it very hard for readers to see the full results and decide what they want to make from there. It's a step down from the previous results. Search is a key feature on the site and we want to get it right.

**Comment by danielwrobert** [comment]
> Search is a key feature on the site and we want to get it right.
That's totally understandable. Unfortunately, Infinite Scroll and ElasticSearch are not working well together. The other option would be to remove ElasticSearch and re-enable Infinite Scroll. But then you're stuck back at square one with issue #111.

> If not, can we remove the # limit to the search results until we have a better solution? I.e. all should show on the first page.

**Comment by danielwrobert** [comment]
> Search is a key feature on the site and we want to get it right.

That's completely understandable. Unfortunately, Infinite Scroll and ElasticSearch are not playing well together. While ES will likely surface better results in many cases, Infinite Scroll is making it much harder to access the full history. We can disable ElasticSearch and re-enable Infinite Scroll and that will work, however, you will be back to square one with issue #111.

> If not, can we remove the # limit to the search results until we have a better solution? I.e. all should show on the first page.

This may be our best option at the moment, based on your needs. From there, we can explore if there is a better solution available. In issue #111, you mentioned that you'd previously used Google Search and were pretty happy with it. Perhaps we can explore if there's a viable option to implement that in your site. But in the meantime, I think displaying all results on the initial page is a good solution. I will plan to work on that tomorrow.

**Comment by danielwrobert** [comment]
This has been updated. Infinite Scroll is active on all post pages, as it was before, and on the search results pages, it is disabled. Pagination is now disabled on the search results pages, as well. The results are displaying all posts on the initial page. No additional styling is needed anymore, as there are no new elements introduced.

We can circle back and explore whether or not there is a feasible Google Search option that we can implement but, for now, I am going to close this out.
