### ISSUE TITLE
email post function -- missing message box + extraneous field

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#145]
We have two concerns about the email post function (in the collection of DO MORE: icons):
1. Previously, as in my last design, it had a message box, which was always used for context. (I.e. "Here's the recipe I was telling you about last night!" etc.) Would love to get that back.
2. There is a second box below the sender email field and it's not clear what it's for -- our best guess is that it's for another email address? Not sure. It's not needed for anything, from what we can see.

Thank you.

**Comment by debperelman** [comment]
Addendum:

3. This feature isn't working consistently. It did for my assistant but neither my husband nor I received the test emails we sent ourselves on different days from different posts.

**Comment by danielwrobert** [comment]
> Previously, as in my last design, it had a message box, which was always used for context. (I.e. "Here's the recipe I was telling you about last night!" etc.) Would love to get that back.

Unfortunately, this feature is currently not available in the Publicize module. I have, however, filed a ticket as a feature request with hopes that this will become available in the future.

> There is a second box below the sender email field and it's not clear what it's for -- our best guess is that it's for another email address? Not sure. It's not needed for anything, from what we can see.

I have removed this input. During testing, I noticed that, if filled in, this was actually causing a problem with sending out the emails. After removing the field, it seems that I am now consistently receiving test emails.
