### ISSUE TITLE
Frequent attempted WordPress.com sign-ins, not by me

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#148]
I have dual verification for signing in so I get texted a 6-digit code whenever there is a new attempt. I get these every day or two, and never when I'm signing in. They often come overnight or at non-work hours for me.

I also, and this might be a separate issue, not sure, am getting a lot of password reset requests (see email below). I was getting them every couple weeks and ignored them but got four in a row this morning. Again, I haven't once tried to reset my password so this seems like a security issue: 

> Someone has requested a password reset for the following account:
> 
> https://wordpress.org/
> 
> Username: deb
> 
> If this was a mistake, just ignore this email and nothing will happen.
> 
> To reset your password, visit the following address:
> 
> <https://login.wordpress.org/wp-login.php?action=rp&key=km9oXzn3NUQ2znGdOUds&login=deb>

**Comment by sarahmonster** [comment]
I can look into this further for you but I can't see any recent records of attempted logins attached to your user—the last ones were nine months or more ago. Is this for your `debsk` user account, or a different account? Can you let me know when you last received a code that you didn't explicitly request, and what the SMS message said exactly?

The second issue is related to your wordpress.org account, which isn't connected to WordPress.com, so we don't have any control over it, unfortunately. I'd recommend making sure your password is quite strong and just ignoring the emails.

**Comment by michiecat** [comment]
@debperelman I'm going to close this issue since the last interaction was in January. If you're still experiencing problems with this, feel free to reopen!
