### ISSUE TITLE
How to add additional author/editor?

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#150]
I'm sorry for such a basic question, but with all of the extra layers of security, I wasn't sure if there are additional steps to take. I need to add a new author/editor to my site. I'd like them to have full access. Thank you.

**Comment by debperelman** [comment]
I'd like to bump this, please. It's been over two weeks. Thanks.

**Comment by michiecat** [comment]
Hi @debperelman! My apologies that we missed responding to these issues earlier. Thanks for checking with us when it comes to security. To add a new author or editor to your site, you can follow the steps here: https://en.support.wordpress.com/adding-users/

Your new authors and editors should also have two-step authentication enabled, for extra security: https://en.support.wordpress.com/security/two-step-authentication/. 

Let me know if you have any other questions.
