### ISSUE TITLE
site is now using a wordpress, not sk, favicon

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#153]
I just noticed this the first time today. Has there been a change? For a site my size, it doesn't look professional without its own logo on it.

**Comment by michiecat** [comment]
@debperelman looks like the setting has moved to the Customizer (https://smittenkitchendotcom.wordpress.com/wp-admin/customize.php?autofocus%5Bsection%5D=title_tagline) - You can find the setting under "Site Icon". I set it to one of the icons you already had uploaded for now. If you have another image to use, you can replace it. Alternatively, you can email us a square image at concierge@wordpress.com and we can add it for you.
