### ISSUE TITLE
URGENT: I need my site verified by Google

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#157]
I need to put verification code in the header of my site to let Google know the site is mine. This is extremely urgent because Google is going to start blocking ads beginning tomorrow, 2/14, on websites that they deem to have "abusive ad experiences" -- while this shouldn't be the case for SK, the only way I can verify this is to have Google run an ad experience test, which it cannot do until the site is claimed as my own.

This is the verification code: 

`<meta name="google-site-verification" content="cpzQnpVAyCpwH6jGDZiWJB3yrs-U-ozrOd8bwHeztSU" />`

It should go in the <head> section, before the first <body> section.

**Comment by wrightcj03** [comment]
Hi @debperelman ,

The verification code has been added.

**Comment by debperelman** [comment]
Thank you. Sadly, this wasn't sufficient, says it still cannot verify. It wants me to use my Google Analytics account instead. It says:

- You must be using the asynchronous tracking code.
- Your tracking code should be in the <head> section of your page.
- You must have the "edit" permission for the Analytics web property.

Here is the asynchronous tracking code:
`
<script async src="https://www.googletagmanager.com/gtag/js?id=GA_TRACKING_ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'GA_TRACKING_ID');
</script>
`

We are to "Paste the following snippet right after the <head> tag on each page of your site. Replace GA_TRACKING_ID with your own Google Analytics tracking ID:" 

My Google Analytics tracking ID is UA-1185356-1

[I don't know how this isn't *already* there because my Google Analytics account is working, but maybe there is some change in it that they need?]

Thank you.

**Comment by debperelman** [comment]
Thank you -- it's not working as it should; I added another note but don't
know how to re-open the closed ticket, want to make sure it is seen.

Thanks,
Deb

**Comment by debperelman** [comment]
Alternatively, could you please create an html file called "google434969ca2f8b990b.html" with the following content:

**google-site-verification: google434969ca2f8b990b.html**

and upload it to smittenkitchen.com, so that it should be accessible at http://www.smittenkitchen.com/google434969ca2f8b990b.html?

(Sorry, I would have just attached the html file, but I was getting an error message when trying to attach.)

**Comment by danielwrobert** [comment]
Hi Deb!

I'm looking into this for you. It looks as if though you do have both the site verification meta and the GA tracking code in your site. But it looks like there's been a recent change where the ga.js is being depreciated in favor of gtag.js.

I will go ahead and update the tracking code and then you can see if that fixes it for you. I'll let you know when it's been deployed.

**Comment by danielwrobert** [comment]
Hi @debperelman,

I added the asynchronous gtag.js code to your site with the tracking info you sent above. Let me know if that works now!

**Comment by debperelman** [comment]
Thanks - looks like that worked. Closing this ticket.
