### ISSUE TITLE
Comment formatting gets a little double-underliney when nested

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/smittenkitchen#98]
Could use a little tweaking:

<img width="693" alt="screen shot 2016-07-14 at 19 53 37" src="https://cloud.githubusercontent.com/assets/376315/16851896/83c7f4ea-49fd-11e6-8826-57b5e8673374.png">

<img width="708" alt="screen shot 2016-07-14 at 19 54 46" src="https://cloud.githubusercontent.com/assets/376315/16851895/83c382fc-49fd-11e6-8be4-6af0ab1e04ad.png">

**Comment by michiecat** [comment]
I just pushed a fix for this. I removed the bottom border from the sub-level comments. Now, only top-level comments get the bottom border. Let me know your thoughts.

**Comment by debperelman** [comment]
This fixes this issue, thank you, so this can be closed. 

I have some bigger concerns about comment formatting (see #126). I'd like to see the names smaller, I think we could tuck the date link next to the reply on the bottom so each comment takes up less space. I think it would also help if the "child" comments were a little more indented or perhaps each had a tiny, subtle [down/right](https://www.google.com/search?q=left+and+down+arrow+symbol&espv=2&biw=1440&bih=779&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiGsKWhkqPOAhUBWD4KHSuFDNEQ_AUIBigB#tbm=isch&q=down+and+right+arrow+symbol&imgrc=8husKSoVlOXhwM%3A) arrow denoting that they're responses from an above thread. As one scrolls down the page and reaches a bunch of response comments in a row, it's not clear that they're not top-level comments. I realize this is on the wrong thread and can copy these additional comments in #126 or a new one. 

Thank you.

**Comment by michiecat** [comment]
@debperelman we'd prefer to have one issue per thread, so I'll copy your comments over to #126 and close this one. Thanks.
